[tools]
cmake = "4.2.1"
ninja = "1.13.1"
python = "3.13.11"

[env]
_.python.venv = { path = ".venv", create = true }
PROJECT_ROOT = "{{cwd}}"

[tasks.pli]
description = "Executa o PLI em todas as instâncias (Necessário licença do gurobi)"
run = """
python python/pli/run.py \
  --input data/instances \
  --output results/pli \
  --time-limit 900 \
  --solver gurobi
"""

[tasks.pli-debug]
description = "Executa o PLI com log detalhado (Necessário licença do gurobi)"
run = """
python python/pli/run.py \
  --input data/instances \
  --output results/pli \
  --time-limit 900 \
  --solver gurobi \
  --tee
"""
